"""Changed exchange_rate to amount

Revision ID: 617c0ef169a4
Revises: 50ec4b5a5098
Create Date: 2024-04-03 19:30:41.316302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '617c0ef169a4'
down_revision: Union[str, None] = '50ec4b5a5098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_history', sa.Column('amount', sa.DECIMAL(), nullable=True))
    op.drop_column('exchange_history', 'exchange_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchange_history', sa.Column('exchange_rate', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('exchange_history', 'amount')
    # ### end Alembic commands ###
