"""Alter columns to be nullable

Revision ID: 8156b3c7665f
Revises: 92be5397c21b
Create Date: 2023-12-02 18:16:17.592418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8156b3c7665f'
down_revision: Union[str, None] = '92be5397c21b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_history', 'is_error',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('request_history', 'exchange_rate',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('request_history', 'exchange_rate',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('request_history', 'is_error',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
