version: "3.8"
services:
  api:
    build: 
      context: ./apps/backend/
      dockerfile: ./docker/python.Dockerfile
    env_file: ./.env
    ports:
      - 9000:9000
  ui:
    build: 
      context: ./apps/frontend/
      dockerfile: ./docker/frontend.Dockerfile
    ports:
      - 9003:8080
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 9001:5432
    volumes:
      - ./db/init/init.sh:/docker-entrypoint-initdb.d/init.sh