version: "3.8"
services:
  api:
    build: 
      context: ./apps/backend/
      dockerfile: ./docker/app.Dockerfile
    env_file: ./backend.env
    ports:
      - 9000:9000
    depends_on:
      db:
        condition: service_healthy
        restart: true
  ui:
    build: 
      context: ./apps/frontend/
      dockerfile: ./docker/frontend.Dockerfile
    volumes:
      - ./frontend.env:/app/.env
    ports:
      - 9003:8080
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 9001:5432
    volumes:
      - ./db/init/init.sh:/docker-entrypoint-initdb.d/init.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "currency"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s  