version: "3.8"
services:
  api:
    build: 
      context: .
      dockerfile: ./docker/python.Dockerfile
    env_file: ./.env
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres