name: Backend workflow

on:
  pull_request:
    branches: [ "master" ]
  push:
    paths:
      - apps/backend/**
      - .github/workflows/reusable/python*
      - .github/workflows/reusable/backend*
jobs:
  backend-lint-and-type-check:
    uses: ./.github/workflows/reusable/python-3.11.6-lint-type-check.yml
  backend-tests:
    uses: ./.github/workflows/reusable/python-3.11.6-tests.yml
    needs: backend-lint-and-type-check